### ISSUE TITLE
BBBCCC Charisma Support Moveset cannot be edited

### ISSUE THREAD

**Issue by barff** [pagewin/MHXXSaveEditor#4]
shows as blank

**Comment by pagewin** [comment]
Occurs on Palicoes that started with BBBCCC moveset. So the editor isn't reading the Palico properly. Set to "020C". This isn't recognized in GameConstants as a valid RNG.

It's due to a sloppy copy and paste job. Charisma values are offset by 1 from the other cat RNGs, and the editor was looking for "020B" which is the same value as regular cats.

Changing the moveset in the editor allows it to be modified
